import asyncio
import json
from contextlib import asynccontextmanager
from typing import Any, Dict

from fastapi import FastAPI, Request

from models import CodeObservation, AgentAction, EpisodeReward, ReviewState
from tasks import TASKS, list_task_ids
from .environment import CodeReviewEnvironment


@asynccontextmanager
async def lifespan(app: FastAPI):
    """Clean up workspace on server shutdown."""
    yield
    env.cleanup()


app = FastAPI(
    title="CodeReview-Env V6",
    description=(
        "Execution-grounded software incident repair benchmark — 10 seeded tasks "
        "spanning code review, memory leaks, network timeouts, service restart gates, "
        "and DB migration ordering. Multi-component reward with diagnosis scoring."
    ),
    version="6.0.0",
    lifespan=lifespan,
)

env = CodeReviewEnvironment()
# Serialize all mutating env calls so concurrent evaluator requests
# cannot interleave reset/step and corrupt episode state.
_env_lock = asyncio.Lock()

# ---------------------------------------------------------------------------
# MCP tool manifest — all 9 AgentAction types, full schemas
# ---------------------------------------------------------------------------
_MCP_TOOLS = [
    {
        "name": "run_tests",
        "description": "Run pytest (full suite or specific path). Preferred over execute_command for testing.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "action_type": {"type": "string", "const": "run_tests"},
                "path": {"type": "string", "description": "Optional test path (e.g. 'tests/test_service.py')"},
            },
            "required": ["action_type"],
        },
    },
    {
        "name": "read_file",
        "description": "Read a file from the sandbox workspace cleanly.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "action_type": {"type": "string", "const": "read_file"},
                "path": {"type": "string", "description": "Relative file path (e.g. 'app/handler.py')"},
            },
            "required": ["action_type", "path"],
        },
    },
    {
        "name": "search_codebase",
        "description": "Grep a regex pattern across all .py files in the workspace.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "action_type": {"type": "string", "const": "search_codebase"},
                "pattern": {"type": "string", "description": "Regex pattern (e.g. 'TIMEOUT|MAX_WORKERS')"},
            },
            "required": ["action_type", "pattern"],
        },
    },
    {
        "name": "inspect_logs",
        "description": "Read service.log / migration.log generated by restart_service.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "action_type": {"type": "string", "const": "inspect_logs"},
            },
            "required": ["action_type"],
        },
    },
    {
        "name": "patch_file",
        "description": "Overwrite a source file with fixed content (triggers delta reward).",
        "inputSchema": {
            "type": "object",
            "properties": {
                "action_type": {"type": "string", "const": "patch_file"},
                "target_file": {"type": "string", "description": "Relative path of file to overwrite"},
                "new_content": {"type": "string", "description": "Complete new file content"},
            },
            "required": ["action_type", "target_file", "new_content"],
        },
    },
    {
        "name": "restart_service",
        "description": "Run app_init.py to apply config/migration changes (tasks 7, 8 & 9).",
        "inputSchema": {
            "type": "object",
            "properties": {
                "action_type": {"type": "string", "const": "restart_service"},
            },
            "required": ["action_type"],
        },
    },
    {
        "name": "submit_fix",
        "description": "Declare fix complete with root-cause analysis; triggers final 6-component grading.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "action_type": {"type": "string", "const": "submit_fix"},
                "root_cause": {
                    "type": "string",
                    "description": "Root-cause analysis scored against per-task diagnosis keywords (15% of reward)",
                },
                "summary": {"type": "string", "description": "Optional human-readable fix summary"},
            },
            "required": ["action_type", "root_cause"],
        },
    },
    {
        "name": "submit_review",
        "description": "Backward-compatible alias for submit_fix.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "action_type": {"type": "string", "const": "submit_review"},
                "summary": {"type": "string"},
                "root_cause": {"type": "string"},
            },
            "required": ["action_type"],
        },
    },
    {
        "name": "execute_command",
        "description": "Escape-hatch: run any bash command in the isolated sandbox.",
        "inputSchema": {
            "type": "object",
            "properties": {
                "action_type": {"type": "string", "const": "execute_command"},
                "command": {"type": "string", "description": "Bash command to run"},
            },
            "required": ["action_type", "command"],
        },
    },
]


@app.get("/health")
async def health_check() -> Dict[str, str]:
    # Return "healthy" as required by openenv validate --url
    return {"status": "healthy"}


@app.get("/metadata")
async def get_metadata() -> Dict[str, Any]:
    """OpenEnv spec: returns environment name and description."""
    return {
        "name": "codereview-env",
        "description": (
            "Execution-grounded software incident repair benchmark — 10 seeded tasks "
            "spanning code review, memory leaks, network timeouts, service restart gates, "
            "and DB migration ordering. Multi-component reward with 6-factor scoring."
        ),
        "version": "2.0.0",
        "author": "Thowfiq Rahman A",
    }


@app.get("/schema")
async def get_schema() -> Dict[str, Any]:
    """OpenEnv spec: returns JSON schemas for action, observation, and state."""
    return {
        "action": AgentAction.model_json_schema(),
        "observation": CodeObservation.model_json_schema(),
        "state": ReviewState.model_json_schema(),
    }


@app.post("/mcp")
async def mcp_endpoint(request: Request) -> Dict[str, Any]:
    """
    OpenEnv spec: JSON-RPC 2.0 MCP endpoint.
    Supports tools/list and tools/call.
    """
    try:
        body = await request.json()
    except Exception:
        body = {}
    method = body.get("method", "")
    req_id = body.get("id", 1)

    # ── tools/list ────────────────────────────────────────────────────────────
    if method == "tools/list":
        return {"jsonrpc": "2.0", "id": req_id, "result": {"tools": _MCP_TOOLS}}

    # ── tools/call ────────────────────────────────────────────────────────────
    if method == "tools/call":
        params = body.get("params", {})
        tool_name = params.get("name", "")
        arguments = params.get("arguments", {})

        # Inject action_type from tool name if caller omitted it
        if "action_type" not in arguments:
            arguments["action_type"] = tool_name

        try:
            action_obj = AgentAction.model_validate(arguments)
        except Exception as e:
            return {
                "jsonrpc": "2.0",
                "id": req_id,
                "error": {"code": -32602, "message": f"Invalid params: {e}"},
            }

        async with _env_lock:
            obs, reward, done, info = env.step(action_obj)

        return {
            "jsonrpc": "2.0",
            "id": req_id,
            "result": {
                "observation": obs.model_dump(),
                "reward": float(reward),
                "done": bool(done),
                "info": info,
            },
        }

    # ── fallback: acknowledge unknown methods ─────────────────────────────────
    return {
        "jsonrpc": "2.0",
        "id": req_id,
        "result": {"status": "ok", "method": method},
    }


@app.get("/tasks")
async def get_tasks() -> Dict[str, list]:
    return {"tasks": list_task_ids()}


@app.post("/reset", response_model=CodeObservation)
async def reset_env(request: Request) -> CodeObservation:
    """
    Start a new episode.  Accepts an optional JSON body::

        {"task_id": "task_3_pr"}

    When ``task_id`` is provided the environment loads that specific task
    instead of advancing the internal round-robin counter.  Omitting the
    body (or sending ``{}``) keeps the default cycling behaviour.
    """
    task_id = None
    try:
        body_bytes = await request.body()
        if body_bytes:
            body = json.loads(body_bytes)
            if isinstance(body, dict):
                task_id = body.get("task_id")
    except Exception:
        task_id = None
    async with _env_lock:
        return env.reset(task_id=task_id)


@app.post("/step")
async def step_env(request: Request) -> Dict[str, Any]:
    raw_text = (await request.body()).decode("utf-8")

    try:
        action_dict = json.loads(raw_text)
        action_obj = AgentAction.model_validate(action_dict)
    except Exception as e:
        # Fall back to a safe no-op so the episode is not silently broken
        action_obj = AgentAction(
            action_type="execute_command",
            command=f"echo 'Parse error — send valid JSON: {str(e)[:120]}'"
        )

    async with _env_lock:
        obs, reward, done, info = env.step(action_obj)

    # Build typed EpisodeReward — prefer 6-component breakdown from submit grading
    # when available, otherwise report raw test pass rate + shaped step reward.
    rb = info.get("reward_breakdown") if info else None
    if rb:
        breakdown = {k: round(float(v), 4) for k, v in rb.items()}
    else:
        test_pass_rate = float(info.get("test_pass_rate", 0.0)) if info else 0.0
        breakdown = {
            "test_pass_rate": round(test_pass_rate, 4),
            "shaped_reward":  round(float(reward), 4),
        }

    typed_reward = EpisodeReward(
        value=round(float(reward), 4),
        is_terminal=bool(done),
        breakdown=breakdown,
    )

    return {
        "observation": obs.model_dump(),
        "reward": float(reward),
        "done": bool(done),
        "info": info,
        "typed_reward": typed_reward.model_dump(),
    }


@app.get("/state")
async def get_state() -> Dict[str, Any]:
    return env.state.model_dump()


def main():
    import uvicorn
    uvicorn.run("server.app:app", host="0.0.0.0", port=7860)


if __name__ == "__main__":
    main()
